name: Build and Test

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup update stable

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
